const actionsTypes ={
    ALBUM_REQUEST: 'ALBUM_REQUEST',
    ALBUM_AVAILABLE: 'ALBUM_AVAILABLE',
    ALBUM_REDIRECT_SUCCESS:'ALBUM_REDIRECT_SUCCESS',
    ALBUM_REDIRECT_FAILURE:'ALBUM_REDIRECT_FAILURE',
    LOAD_FONTS: 'LOAD_FONTS',
    LOAD_FONTS_SUCCESS: 'LOAD_FONTS_SUCCESS',
    FETCHING:'FETCHING'
    
    
}

export default actionsTypes;